name: GitHub Actions Dockerhub
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and tag image
        run: docker build Dockerfile . --tag pausi/test-action-pccp:v1
      - name: Push image to Dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_SECRET }} && docker push pausi/test-action-pccp:v1